[bits 32]
section .text
global _gdt_flush
global _tss_flush

_gdt_flush:
    mov eax, [esp+4]  ; Get the pointer to the GDT, passed as a parameter.
    lgdt [eax]        ; Load the new GDT pointer

    mov ax, 0x10      ; 0x10 is the offset in the GDT to our data segment
    mov ds, ax        ; Load all data segment selectors
    mov es, ax
    mov fs, ax
    mov gs, ax
    mov ss, ax
    jmp 0x08:.flush   ; 0x08 is the offset to our code segment: Far jump!
.flush:
    ret

_tss_flush:
    mov ax, 0x2B      ; 0x2B is the index of our TSS (5 * 8 = 40, 40 = 0x28. Or 3 for RPL = 0x2B). We use 0x2B.
    ltr ax            ; Load the Task Register
    ret
